Repository feedback-forms/feedback-forms, pull requests merged in 2025-02, with the labels that each got.

#68 Fix: Enhance Target Survey Template With Improved Styling and Interaction
  resources/views/survey_templates/target.blade.php
Labels: enhancement

#69 Feat: Add Admin Panel with Livewire Component and Localization
  app/Livewire/Admin/Panel.php
  app/Models/InviteToken.php
  lang/de/admin.php
  resources/views/livewire/admin/panel.blade.php
  routes/web.php
Labels: frontend

#70 Feat: Add User Management Interface
  app/Livewire/Admin/Users.php
  lang/de/admin.php
  resources/views/livewire/admin/users.blade.php
  routes/web.php
Labels: frontend

#83 Bugfix: Filterlogik Surveys mit JS jetzt Clientseitig
  resources/css/surveys-page.css
  resources/views/layouts/app.blade.php
  resources/views/livewire/surveys/overview.blade.php
Labels: bug

#106 DB setup deployment
  deployments/db-setup-job.yaml
Labels: enhancement
