Repository feedback-forms/feedback-forms, pull requests merged in 2025-03, with the labels that each got.

#119 Improve UserSeeder to handle existing admin user
  database/seeders/UserSeeder.php
Labels: backend

#118 disable submission when previewing templates
  resources/views/components/primary-button.blade.php
  resources/views/survey_templates/smiley.blade.php
  resources/views/survey_templates/table.blade.php
  resources/views/survey_templates/target.blade.php
Labels: bug, frontend

#108 Enhance Error Message on Welcome Site
  resources/views/surveys/access.blade.php
  resources/views/welcome.blade.php
Labels: enhancement

#105 BugFix: Centering on Survey Submission
  resources/views/survey_templates/checkbox_respond.blade.php
  resources/views/survey_templates/smiley_respond.blade.php
  resources/views/survey_templates/table_respond.blade.php
  resources/views/survey_templates/target_respond.blade.php
  resources/views/surveys/respond.blade.php
Labels: enhancement, frontend

#121 Add QR code support for survey access
  app/Http/Controllers/WelcomeController.php
  lang/de/surveys.php
  lang/en/surveys.php
  package-lock.json
  package.json
  resources/js/app.js
  resources/views/livewire/surveys/edit.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: frontend, backend

#133 fix optional email signup
  resources/views/livewire/pages/auth/register.blade.php
Labels: bug, frontend

#126 Docs: Add Readme
  README.md
Labels: documentation

#127 Change Result Handling: Migrated from JSON to Entity Relationship Model 1/2
  .gitignore
  Database_Relations.md
  app/Console/Commands/MigrateSurveyResultsData.php
  app/Models/ResponseValue.php
  app/Models/Result.php
  app/Services/SurveyService.php
  composer.lock
  database/migrations/2025_02_27_090639_update_results_table_value_to_json.php
  database/migrations/2025_03_11_162154_create_response_values_table.php
  database/migrations/2025_03_11_164301_update_results_table_value_to_nullable.php
Labels: backend

#128 Fix Admin User Interface Issues and Add Temporary Password Generation
  app/Livewire/Admin/Panel.php
  app/Livewire/Admin/Users.php
  lang/de/admin.php
  lang/en/admin.php
  resources/views/livewire/admin/panel.blade.php
  resources/views/livewire/admin/users.blade.php
Labels: frontend, backend

#132 let invite tokens to expire and add validation to check for valid token
  app/Models/Registerkey.php
  app/Rules/RegisterKeyExpired.php
  database/migrations/0001_01_01_000000_create_registerkeys_table.php
  database/seeders/RegisterKeySeeder.php
  lang/de/register.php
  resources/views/livewire/pages/auth/register.blade.php
Labels: frontend, backend

#130 Add Survey Statistics Feature with Comprehensive Data Visualization
  app/Http/Controllers/SurveyStatisticsController.php
  app/Models/Feedback.php
  app/Models/Question_template.php
  app/Policies/FeedbackPolicy.php
  app/Providers/AppServiceProvider.php
  app/Services/SurveyService.php
  resources/views/livewire/surveys/overview.blade.php
  resources/views/surveys/statistics.blade.php
  routes/web.php
  statistics-page.html
  tests/Feature/SurveyStatisticsTest.php
  tests/Unit/SurveyServiceTest.php
Labels: frontend, backend

#134 Invite Token Managment
  app/Livewire/Admin/InviteToken.php
  app/Livewire/Admin/Panel.php
  app/Services/RegisterKeyService.php
  lang/de/admin.php
  lang/de/invite_token.php
  resources/views/components/invite-token-list.blade.php
  resources/views/livewire/admin/invite-token.blade.php
  resources/views/livewire/admin/panel.blade.php
  resources/views/livewire/layout/navigation.blade.php
  routes/web.php
Labels: frontend

#147 add option to revoke invite token
  app/Livewire/Admin/InviteToken.php
  app/Services/RegisterKeyService.php
  lang/de/invite_token.php
  resources/views/components/dropdown.blade.php
  resources/views/components/invite-token-list.blade.php
Labels: enhancement, frontend

#144 Enhance Filtering of Surveys
  Database_Relations.md
  app/Livewire/Surveys/Overview.php
  lang/de/surveys.php
  lang/en/surveys.php
  resources/css/surveys-page.css
  resources/js/app.js
  resources/js/survey-filter.js
  resources/views/livewire/surveys/overview.blade.php
Labels: enhancement, frontend

#152 Change Token duration
  app/Livewire/Admin/InviteToken.php
  app/Services/RegisterKeyService.php
  lang/de/invite_token.php
  resources/views/components/invite-token-list.blade.php
  resources/views/components/primary-button.blade.php
  resources/views/livewire/admin/invite-token.blade.php
Labels: enhancement, frontend

#168 Normailze Surveys
  app/Http/Controllers/SurveyController.php
  app/Livewire/Surveys/Edit.php
  app/Models/Department.php
  app/Models/Feedback.php
  app/Models/GradeLevel.php
  app/Models/SchoolClass.php
  app/Models/SchoolYear.php
  app/Models/Subject.php
  app/Services/SurveyService.php
  database/migrations/2025_01_21_104948_create_feedback_table.php
  resources/views/livewire/surveys/edit.blade.php
  resources/views/survey_templates/checkbox_respond.blade.php
  resources/views/survey_templates/smiley_respond.blade.php
  resources/views/survey_templates/table_respond.blade.php
  resources/views/survey_templates/target_respond.blade.php
  resources/views/surveys/create.blade.php
  resources/views/surveys/respond.blade.php
Labels: enhancement, frontend, backend

#166 Aggregation Logic Admin Panel
  app/Http/Controllers/TestController.php
  app/Livewire/Admin/SurveyAggregation.php
  app/Models/Question.php
  app/Services/SurveyAggregationService.php
  database/migrations/2025_03_17_101844_add_category_to_questions_table.php
  database/seeders/CategoryAssignmentSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/SurveyResponseSeeder.php
  lang/de/admin.php
  lang/en/admin.php
  resources/views/livewire/admin/panel.blade.php
  resources/views/livewire/admin/survey-aggregation.blade.php
  resources/views/test-translation.blade.php
  routes/web.php
Labels: frontend, backend

#170 Add Checkbox Feedback Survey Type
  app/Models/Feedback.php
  app/Services/SurveyAggregationService.php
  app/Services/SurveyService.php
  database/seeders/CheckboxSurveySetupSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/QuestionTemplateSeeder.php
  lang/de/admin.php
  lang/de/surveys.php
  lang/en/admin.php
  lang/en/surveys.php
  resources/views/livewire/admin/panel.blade.php
  resources/views/livewire/admin/survey-aggregation.blade.php
  resources/views/livewire/layout/navigation.blade.php
  resources/views/survey_templates/checkbox_respond.blade.php
  resources/views/surveys/respond.blade.php
  resources/views/surveys/statistics.blade.php
  resources/views/surveys/statistics/checkbox_survey.blade.php
  resources/views/surveys/statistics/components/checkbox_distribution.blade.php
  resources/views/surveys/statistics/components/open_feedback.blade.php
  resources/views/surveys/statistics/default_survey.blade.php
Labels: frontend, backend

#175 Fix: Disable auto-refresh in Vite configuration for improved performance.
  vite.config.js
Labels: backend
