Repository feedback-forms/feedback-forms, pull requests merged in 2025-01, with the labels that each got.

#36 Update issue templates
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: enhancement

#43 Feat: Add E-Mail Verification System
  Makefile
  app/Models/User.php
  app/Notifications/CustomVerifyEmail.php
  config/mail.php
  docker-compose.yml
  resources/views/auth/verify.blade.php
Labels: backend

#45 add welcome page and translations
  .env.example
  app/Http/Controllers/WelcomeController.php
  composer.json
  composer.lock
  config/blade-fontawesome.php
  config/blade-icons.php
  lang/de/welcome.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: frontend

#39 Added Models with fitting migrations, added relationships, filled mig…
  app/Models/Feedback.php
  app/Models/Feedback_template.php
  app/Models/Question.php
  app/Models/Question_template.php
  app/Models/Registerkey.php
  app/Models/Result.php
  app/Models/User.php
  database/migrations/0001_01_01_000000_create_users_table.php
  database/migrations/2025_01_21_104916_create_results_table.php
  database/migrations/2025_01_21_104933_create_questions_table.php
  database/migrations/2025_01_21_104948_create_feedback_table.php
  database/migrations/2025_01_21_105218_create_feedback_templates_table.php
  database/migrations/2025_01_21_105231_create_question_templates_table.php
  database/migrations/2025_01_21_105251_create_registerkeys_table.php
Labels: backend

#49 Deployment Workflow
  .github/workflows/build.yml
  .github/workflows/ci-cd.yml
  .github/workflows/deploy.yml
  Dockerfile
  deployments/app-deployment.yaml
  deployments/db-setup-job.yaml
  deployments/ingress.yaml
  deployments/nginx-configmap.yaml
  deployments/postgres-deployment.yaml
  deployments/queue-deployment.yaml
Labels: enhancement, backend

#51 Surveys Overview
  app/Http/Controllers/WelcomeController.php
  app/Livewire/Surveys/Overview.php
  config/livewire.php
  lang/de/surveys.php
  public/img/preview.png
  resources/views/components/chip.blade.php
  resources/views/livewire/surveys/overview.blade.php
  resources/views/vendor/livewire/bootstrap.blade.php
  resources/views/vendor/livewire/simple-bootstrap.blade.php
  resources/views/vendor/livewire/simple-tailwind.blade.php
  resources/views/vendor/livewire/tailwind.blade.php
  routes/auth.php
  routes/web.php
  tests/Feature/Livewire/Surveys/OverviewTest.php
Labels: frontend

#37 New: Revision Login/Register (only Frontend)
  lang/de/login.php
  lang/de/register.php
  resources/views/components/footer.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/livewire/pages/auth/login.blade.php
  resources/views/livewire/pages/auth/register.blade.php
  resources/views/welcome.blade.php
Labels: enhancement, frontend

#57 Feedback - Table
  .github/workflows/ci-cd.yml
  Makefile
  app/Http/Controllers/SurveyController.php
  app/Models/User.php
  resources/views/survey_templates/table.blade.php
  routes/web.php
Labels: frontend

#59 Feat: Templates
  .gitignore
  app/Http/Controllers/SurveyController.php
  app/Livewire/Templates/Overview.php
  lang/de/templates.php
  package-lock.json
  package.json
  resources/js/app.js
  resources/views/layouts/app.blade.php
  resources/views/livewire/templates/overview.blade.php
  resources/views/survey_templates/target.blade.php
  routes/auth.php
  routes/web.php
  tests/Feature/Livewire/Templates/OverviewTest.php
Labels: frontend
